/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Create Recovery Code for Identity Request Body
 * @export
 * @interface CreateRecoveryCodeForIdentityBody
 */
export interface CreateRecoveryCodeForIdentityBody {
    /**
     * Code Expires In
     * 
     * The recovery code will expire after that amount of time has passed. Defaults to the configuration value of
     * `selfservice.methods.code.config.lifespan`.
     * @type {string}
     * @memberof CreateRecoveryCodeForIdentityBody
     */
    expires_in?: string;
    /**
     * Identity to Recover
     * 
     * The identity's ID you wish to recover.
     * @type {string}
     * @memberof CreateRecoveryCodeForIdentityBody
     */
    identity_id: string;
}

/**
 * Check if a given object implements the CreateRecoveryCodeForIdentityBody interface.
 */
export function instanceOfCreateRecoveryCodeForIdentityBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identity_id" in value;

    return isInstance;
}

export function CreateRecoveryCodeForIdentityBodyFromJSON(json: any): CreateRecoveryCodeForIdentityBody {
    return CreateRecoveryCodeForIdentityBodyFromJSONTyped(json, false);
}

export function CreateRecoveryCodeForIdentityBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecoveryCodeForIdentityBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expires_in': !exists(json, 'expires_in') ? undefined : json['expires_in'],
        'identity_id': json['identity_id'],
    };
}

export function CreateRecoveryCodeForIdentityBodyToJSON(value?: CreateRecoveryCodeForIdentityBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expires_in': value.expires_in,
        'identity_id': value.identity_id,
    };
}

