/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MemberInvite } from './MemberInvite';
import {
    MemberInviteFromJSON,
    MemberInviteFromJSONTyped,
    MemberInviteToJSON,
} from './MemberInvite';

/**
 * 
 * @export
 * @interface CreateInviteResponse
 */
export interface CreateInviteResponse {
    /**
     * A list of all invites for this resource
     * @type {Array<MemberInvite>}
     * @memberof CreateInviteResponse
     */
    all_invites: Array<MemberInvite>;
    /**
     * 
     * @type {MemberInvite}
     * @memberof CreateInviteResponse
     */
    created_invite: MemberInvite;
}

/**
 * Check if a given object implements the CreateInviteResponse interface.
 */
export function instanceOfCreateInviteResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "all_invites" in value;
    isInstance = isInstance && "created_invite" in value;

    return isInstance;
}

export function CreateInviteResponseFromJSON(json: any): CreateInviteResponse {
    return CreateInviteResponseFromJSONTyped(json, false);
}

export function CreateInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInviteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'all_invites': ((json['all_invites'] as Array<any>).map(MemberInviteFromJSON)),
        'created_invite': MemberInviteFromJSON(json['created_invite']),
    };
}

export function CreateInviteResponseToJSON(value?: CreateInviteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'all_invites': ((value.all_invites as Array<any>).map(MemberInviteToJSON)),
        'created_invite': MemberInviteToJSON(value.created_invite),
    };
}

