/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Deleted Session Count
 * @export
 * @interface DeleteMySessionsCount
 */
export interface DeleteMySessionsCount {
    /**
     * The number of sessions that were revoked.
     * @type {number}
     * @memberof DeleteMySessionsCount
     */
    count?: number;
}

/**
 * Check if a given object implements the DeleteMySessionsCount interface.
 */
export function instanceOfDeleteMySessionsCount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteMySessionsCountFromJSON(json: any): DeleteMySessionsCount {
    return DeleteMySessionsCountFromJSONTyped(json, false);
}

export function DeleteMySessionsCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMySessionsCount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function DeleteMySessionsCountToJSON(value?: DeleteMySessionsCount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
    };
}

