/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GenericErrorContent } from './GenericErrorContent';
import {
    GenericErrorContentFromJSON,
    GenericErrorContentFromJSONTyped,
    GenericErrorContentToJSON,
} from './GenericErrorContent';

/**
 * Error responses are sent when an error (e.g. unauthorized, bad request, ...) occurred.
 * @export
 * @interface GenericError
 */
export interface GenericError {
    /**
     * The status code
     * @type {number}
     * @memberof GenericError
     */
    code?: number;
    /**
     * Debug information
     * 
     * This field is often not exposed to protect against leaking
     * sensitive information.
     * @type {string}
     * @memberof GenericError
     */
    debug?: string;
    /**
     * Further error details
     * @type {any}
     * @memberof GenericError
     */
    details?: any | null;
    /**
     * 
     * @type {GenericErrorContent}
     * @memberof GenericError
     */
    error?: GenericErrorContent;
    /**
     * The error ID
     * 
     * Useful when trying to identify various errors in application logic.
     * @type {string}
     * @memberof GenericError
     */
    id?: string;
    /**
     * Error message
     * 
     * The error's message.
     * @type {string}
     * @memberof GenericError
     */
    message: string;
    /**
     * A human-readable reason for the error
     * @type {string}
     * @memberof GenericError
     */
    reason?: string;
    /**
     * The request ID
     * 
     * The request ID is often exposed internally in order to trace
     * errors across service architectures. This is often a UUID.
     * @type {string}
     * @memberof GenericError
     */
    request?: string;
    /**
     * The status description
     * @type {string}
     * @memberof GenericError
     */
    status?: string;
}

/**
 * Check if a given object implements the GenericError interface.
 */
export function instanceOfGenericError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function GenericErrorFromJSON(json: any): GenericError {
    return GenericErrorFromJSONTyped(json, false);
}

export function GenericErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'debug': !exists(json, 'debug') ? undefined : json['debug'],
        'details': !exists(json, 'details') ? undefined : json['details'],
        'error': !exists(json, 'error') ? undefined : GenericErrorContentFromJSON(json['error']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'message': json['message'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'request': !exists(json, 'request') ? undefined : json['request'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function GenericErrorToJSON(value?: GenericError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'debug': value.debug,
        'details': value.details,
        'error': GenericErrorContentToJSON(value.error),
        'id': value.id,
        'message': value.message,
        'reason': value.reason,
        'request': value.request,
        'status': value.status,
    };
}

