/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * and so on.
 * @export
 */
export const IdentityCredentialsType = {
    Password: 'password',
    Totp: 'totp',
    Oidc: 'oidc',
    Webauthn: 'webauthn',
    LookupSecret: 'lookup_secret',
    Code: 'code'
} as const;
export type IdentityCredentialsType = typeof IdentityCredentialsType[keyof typeof IdentityCredentialsType];


export function IdentityCredentialsTypeFromJSON(json: any): IdentityCredentialsType {
    return IdentityCredentialsTypeFromJSONTyped(json, false);
}

export function IdentityCredentialsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityCredentialsType {
    return json as IdentityCredentialsType;
}

export function IdentityCredentialsTypeToJSON(value?: IdentityCredentialsType | null): any {
    return value as any;
}

