/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IdentityWithCredentialsPasswordConfig } from './IdentityWithCredentialsPasswordConfig';
import {
    IdentityWithCredentialsPasswordConfigFromJSON,
    IdentityWithCredentialsPasswordConfigFromJSONTyped,
    IdentityWithCredentialsPasswordConfigToJSON,
} from './IdentityWithCredentialsPasswordConfig';

/**
 * Create Identity and Import Password Credentials
 * @export
 * @interface IdentityWithCredentialsPassword
 */
export interface IdentityWithCredentialsPassword {
    /**
     * 
     * @type {IdentityWithCredentialsPasswordConfig}
     * @memberof IdentityWithCredentialsPassword
     */
    config?: IdentityWithCredentialsPasswordConfig;
}

/**
 * Check if a given object implements the IdentityWithCredentialsPassword interface.
 */
export function instanceOfIdentityWithCredentialsPassword(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IdentityWithCredentialsPasswordFromJSON(json: any): IdentityWithCredentialsPassword {
    return IdentityWithCredentialsPasswordFromJSONTyped(json, false);
}

export function IdentityWithCredentialsPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityWithCredentialsPassword {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': !exists(json, 'config') ? undefined : IdentityWithCredentialsPasswordConfigFromJSON(json['config']),
    };
}

export function IdentityWithCredentialsPasswordToJSON(value?: IdentityWithCredentialsPassword | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': IdentityWithCredentialsPasswordConfigToJSON(value.config),
    };
}

