/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The state can either be `active` or `inactive`.
 * @export
 */
export const IdentityState = {
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type IdentityState = typeof IdentityState[keyof typeof IdentityState];


export function IdentityStateFromJSON(json: any): IdentityState {
    return IdentityStateFromJSONTyped(json, false);
}

export function IdentityStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityState {
    return json as IdentityState;
}

export function IdentityStateToJSON(value?: IdentityState | null): any {
    return value as any;
}

