/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsReady200Response
 */
export interface IsReady200Response {
    /**
     * Always "ok".
     * @type {string}
     * @memberof IsReady200Response
     */
    status: string;
}

/**
 * Check if a given object implements the IsReady200Response interface.
 */
export function instanceOfIsReady200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function IsReady200ResponseFromJSON(json: any): IsReady200Response {
    return IsReady200ResponseFromJSONTyped(json, false);
}

export function IsReady200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsReady200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function IsReady200ResponseToJSON(value?: IsReady200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

