/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AcceptOAuth2ConsentRequestSession } from './AcceptOAuth2ConsentRequestSession';
import {
    AcceptOAuth2ConsentRequestSessionFromJSON,
    AcceptOAuth2ConsentRequestSessionFromJSONTyped,
    AcceptOAuth2ConsentRequestSessionToJSON,
} from './AcceptOAuth2ConsentRequestSession';
import type { OAuth2ConsentRequest } from './OAuth2ConsentRequest';
import {
    OAuth2ConsentRequestFromJSON,
    OAuth2ConsentRequestFromJSONTyped,
    OAuth2ConsentRequestToJSON,
} from './OAuth2ConsentRequest';
import type { OAuth2ConsentSessionExpiresAt } from './OAuth2ConsentSessionExpiresAt';
import {
    OAuth2ConsentSessionExpiresAtFromJSON,
    OAuth2ConsentSessionExpiresAtFromJSONTyped,
    OAuth2ConsentSessionExpiresAtToJSON,
} from './OAuth2ConsentSessionExpiresAt';

/**
 * A completed OAuth 2.0 Consent Session.
 * @export
 * @interface OAuth2ConsentSession
 */
export interface OAuth2ConsentSession {
    /**
     * 
     * @type {OAuth2ConsentRequest}
     * @memberof OAuth2ConsentSession
     */
    consent_request?: OAuth2ConsentRequest;
    /**
     * 
     * @type {OAuth2ConsentSessionExpiresAt}
     * @memberof OAuth2ConsentSession
     */
    expires_at?: OAuth2ConsentSessionExpiresAt;
    /**
     * 
     * @type {Array<string>}
     * @memberof OAuth2ConsentSession
     */
    grant_access_token_audience?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OAuth2ConsentSession
     */
    grant_scope?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof OAuth2ConsentSession
     */
    handled_at?: Date;
    /**
     * Remember Consent
     * 
     * Remember, if set to true, tells ORY Hydra to remember this consent authorization and reuse it if the same
     * client asks the same user for the same, or a subset of, scope.
     * @type {boolean}
     * @memberof OAuth2ConsentSession
     */
    remember?: boolean;
    /**
     * Remember Consent For
     * 
     * RememberFor sets how long the consent authorization should be remembered for in seconds. If set to `0`, the
     * authorization will be remembered indefinitely.
     * @type {number}
     * @memberof OAuth2ConsentSession
     */
    remember_for?: number;
    /**
     * 
     * @type {AcceptOAuth2ConsentRequestSession}
     * @memberof OAuth2ConsentSession
     */
    session?: AcceptOAuth2ConsentRequestSession;
}

/**
 * Check if a given object implements the OAuth2ConsentSession interface.
 */
export function instanceOfOAuth2ConsentSession(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OAuth2ConsentSessionFromJSON(json: any): OAuth2ConsentSession {
    return OAuth2ConsentSessionFromJSONTyped(json, false);
}

export function OAuth2ConsentSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2ConsentSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'consent_request': !exists(json, 'consent_request') ? undefined : OAuth2ConsentRequestFromJSON(json['consent_request']),
        'expires_at': !exists(json, 'expires_at') ? undefined : OAuth2ConsentSessionExpiresAtFromJSON(json['expires_at']),
        'grant_access_token_audience': !exists(json, 'grant_access_token_audience') ? undefined : json['grant_access_token_audience'],
        'grant_scope': !exists(json, 'grant_scope') ? undefined : json['grant_scope'],
        'handled_at': !exists(json, 'handled_at') ? undefined : (new Date(json['handled_at'])),
        'remember': !exists(json, 'remember') ? undefined : json['remember'],
        'remember_for': !exists(json, 'remember_for') ? undefined : json['remember_for'],
        'session': !exists(json, 'session') ? undefined : AcceptOAuth2ConsentRequestSessionFromJSON(json['session']),
    };
}

export function OAuth2ConsentSessionToJSON(value?: OAuth2ConsentSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'consent_request': OAuth2ConsentRequestToJSON(value.consent_request),
        'expires_at': OAuth2ConsentSessionExpiresAtToJSON(value.expires_at),
        'grant_access_token_audience': value.grant_access_token_audience,
        'grant_scope': value.grant_scope,
        'handled_at': value.handled_at === undefined ? undefined : (value.handled_at.toISOString()),
        'remember': value.remember,
        'remember_for': value.remember_for,
        'session': AcceptOAuth2ConsentRequestSessionToJSON(value.session),
    };
}

