/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IdentityCredentialsType } from './IdentityCredentialsType';
import {
    IdentityCredentialsTypeFromJSON,
    IdentityCredentialsTypeFromJSONTyped,
    IdentityCredentialsTypeToJSON,
} from './IdentityCredentialsType';
import type { OAuth2LoginRequest } from './OAuth2LoginRequest';
import {
    OAuth2LoginRequestFromJSON,
    OAuth2LoginRequestFromJSONTyped,
    OAuth2LoginRequestToJSON,
} from './OAuth2LoginRequest';
import type { UiContainer } from './UiContainer';
import {
    UiContainerFromJSON,
    UiContainerFromJSONTyped,
    UiContainerToJSON,
} from './UiContainer';

/**
 * 
 * @export
 * @interface RegistrationFlow
 */
export interface RegistrationFlow {
    /**
     * 
     * @type {IdentityCredentialsType}
     * @memberof RegistrationFlow
     */
    active?: IdentityCredentialsType;
    /**
     * ExpiresAt is the time (UTC) when the flow expires. If the user still wishes to log in,
     * a new flow has to be initiated.
     * @type {Date}
     * @memberof RegistrationFlow
     */
    expires_at: Date;
    /**
     * ID represents the flow's unique ID. When performing the registration flow, this
     * represents the id in the registration ui's query parameter: http://<selfservice.flows.registration.ui_url>/?flow=<id>
     * @type {string}
     * @memberof RegistrationFlow
     */
    id: string;
    /**
     * IssuedAt is the time (UTC) when the flow occurred.
     * @type {Date}
     * @memberof RegistrationFlow
     */
    issued_at: Date;
    /**
     * Ory OAuth 2.0 Login Challenge.
     * 
     * This value is set using the `login_challenge` query parameter of the registration and login endpoints.
     * If set will cooperate with Ory OAuth2 and OpenID to act as an OAuth2 server / OpenID Provider.
     * @type {string}
     * @memberof RegistrationFlow
     */
    oauth2_login_challenge?: string;
    /**
     * 
     * @type {OAuth2LoginRequest}
     * @memberof RegistrationFlow
     */
    oauth2_login_request?: OAuth2LoginRequest;
    /**
     * 
     * @type {string}
     * @memberof RegistrationFlow
     */
    organization_id?: string | null;
    /**
     * RequestURL is the initial URL that was requested from Ory Kratos. It can be used
     * to forward information contained in the URL's path or query for example.
     * @type {string}
     * @memberof RegistrationFlow
     */
    request_url: string;
    /**
     * ReturnTo contains the requested return_to URL.
     * @type {string}
     * @memberof RegistrationFlow
     */
    return_to?: string;
    /**
     * SessionTokenExchangeCode holds the secret code that the client can use to retrieve a session token after the flow has been completed.
     * This is only set if the client has requested a session token exchange code, and if the flow is of type "api",
     * and only on creating the flow.
     * @type {string}
     * @memberof RegistrationFlow
     */
    session_token_exchange_code?: string;
    /**
     * State represents the state of this request:
     * 
     * choose_method: ask the user to choose a method (e.g. registration with email)
     * sent_email: the email has been sent to the user
     * passed_challenge: the request was successful and the registration challenge was passed.
     * @type {any}
     * @memberof RegistrationFlow
     */
    state: any | null;
    /**
     * TransientPayload is used to pass data from the registration to a webhook
     * @type {object}
     * @memberof RegistrationFlow
     */
    transient_payload?: object;
    /**
     * The flow type can either be `api` or `browser`.
     * @type {string}
     * @memberof RegistrationFlow
     */
    type: string;
    /**
     * 
     * @type {UiContainer}
     * @memberof RegistrationFlow
     */
    ui: UiContainer;
}

/**
 * Check if a given object implements the RegistrationFlow interface.
 */
export function instanceOfRegistrationFlow(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "expires_at" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "issued_at" in value;
    isInstance = isInstance && "request_url" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "ui" in value;

    return isInstance;
}

export function RegistrationFlowFromJSON(json: any): RegistrationFlow {
    return RegistrationFlowFromJSONTyped(json, false);
}

export function RegistrationFlowFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationFlow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : IdentityCredentialsTypeFromJSON(json['active']),
        'expires_at': (new Date(json['expires_at'])),
        'id': json['id'],
        'issued_at': (new Date(json['issued_at'])),
        'oauth2_login_challenge': !exists(json, 'oauth2_login_challenge') ? undefined : json['oauth2_login_challenge'],
        'oauth2_login_request': !exists(json, 'oauth2_login_request') ? undefined : OAuth2LoginRequestFromJSON(json['oauth2_login_request']),
        'organization_id': !exists(json, 'organization_id') ? undefined : json['organization_id'],
        'request_url': json['request_url'],
        'return_to': !exists(json, 'return_to') ? undefined : json['return_to'],
        'session_token_exchange_code': !exists(json, 'session_token_exchange_code') ? undefined : json['session_token_exchange_code'],
        'state': json['state'],
        'transient_payload': !exists(json, 'transient_payload') ? undefined : json['transient_payload'],
        'type': json['type'],
        'ui': UiContainerFromJSON(json['ui']),
    };
}

export function RegistrationFlowToJSON(value?: RegistrationFlow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': IdentityCredentialsTypeToJSON(value.active),
        'expires_at': (value.expires_at.toISOString()),
        'id': value.id,
        'issued_at': (value.issued_at.toISOString()),
        'oauth2_login_challenge': value.oauth2_login_challenge,
        'oauth2_login_request': OAuth2LoginRequestToJSON(value.oauth2_login_request),
        'organization_id': value.organization_id,
        'request_url': value.request_url,
        'return_to': value.return_to,
        'session_token_exchange_code': value.session_token_exchange_code,
        'state': value.state,
        'transient_payload': value.transient_payload,
        'type': value.type,
        'ui': UiContainerToJSON(value.ui),
    };
}

