/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Namespace } from './Namespace';
import {
    NamespaceFromJSON,
    NamespaceFromJSONTyped,
    NamespaceToJSON,
} from './Namespace';

/**
 * Relationship Namespace List
 * @export
 * @interface RelationshipNamespaces
 */
export interface RelationshipNamespaces {
    /**
     * 
     * @type {Array<Namespace>}
     * @memberof RelationshipNamespaces
     */
    namespaces?: Array<Namespace>;
}

/**
 * Check if a given object implements the RelationshipNamespaces interface.
 */
export function instanceOfRelationshipNamespaces(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RelationshipNamespacesFromJSON(json: any): RelationshipNamespaces {
    return RelationshipNamespacesFromJSONTyped(json, false);
}

export function RelationshipNamespacesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipNamespaces {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'namespaces': !exists(json, 'namespaces') ? undefined : ((json['namespaces'] as Array<any>).map(NamespaceFromJSON)),
    };
}

export function RelationshipNamespacesToJSON(value?: RelationshipNamespaces | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'namespaces': value.namespaces === undefined ? undefined : ((value.namespaces as Array<any>).map(NamespaceToJSON)),
    };
}

