/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectBrandingColors } from './ProjectBrandingColors';
import {
    ProjectBrandingColorsFromJSON,
    ProjectBrandingColorsFromJSONTyped,
    ProjectBrandingColorsToJSON,
} from './ProjectBrandingColors';

/**
 * 
 * @export
 * @interface SetProjectBrandingThemeBody
 */
export interface SetProjectBrandingThemeBody {
    /**
     * Favicon Type
     * @type {string}
     * @memberof SetProjectBrandingThemeBody
     */
    favicon_type?: string;
    /**
     * Favicon URL
     * @type {string}
     * @memberof SetProjectBrandingThemeBody
     */
    favicon_url?: string;
    /**
     * Logo type
     * @type {string}
     * @memberof SetProjectBrandingThemeBody
     */
    logo_type?: string;
    /**
     * Logo URL
     * @type {string}
     * @memberof SetProjectBrandingThemeBody
     */
    logo_url?: string;
    /**
     * Branding name
     * @type {string}
     * @memberof SetProjectBrandingThemeBody
     */
    name?: string;
    /**
     * 
     * @type {ProjectBrandingColors}
     * @memberof SetProjectBrandingThemeBody
     */
    theme?: ProjectBrandingColors;
}

/**
 * Check if a given object implements the SetProjectBrandingThemeBody interface.
 */
export function instanceOfSetProjectBrandingThemeBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SetProjectBrandingThemeBodyFromJSON(json: any): SetProjectBrandingThemeBody {
    return SetProjectBrandingThemeBodyFromJSONTyped(json, false);
}

export function SetProjectBrandingThemeBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetProjectBrandingThemeBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'favicon_type': !exists(json, 'favicon_type') ? undefined : json['favicon_type'],
        'favicon_url': !exists(json, 'favicon_url') ? undefined : json['favicon_url'],
        'logo_type': !exists(json, 'logo_type') ? undefined : json['logo_type'],
        'logo_url': !exists(json, 'logo_url') ? undefined : json['logo_url'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'theme': !exists(json, 'theme') ? undefined : ProjectBrandingColorsFromJSON(json['theme']),
    };
}

export function SetProjectBrandingThemeBodyToJSON(value?: SetProjectBrandingThemeBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'favicon_type': value.favicon_type,
        'favicon_url': value.favicon_url,
        'logo_type': value.logo_type,
        'logo_url': value.logo_url,
        'name': value.name,
        'theme': ProjectBrandingColorsToJSON(value.theme),
    };
}

