/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Update Settings Flow with Password Method
 * @export
 * @interface UpdateSettingsFlowWithPasswordMethod
 */
export interface UpdateSettingsFlowWithPasswordMethod {
    /**
     * CSRFToken is the anti-CSRF token
     * @type {string}
     * @memberof UpdateSettingsFlowWithPasswordMethod
     */
    csrf_token?: string;
    /**
     * Method
     * 
     * Should be set to password when trying to update a password.
     * @type {string}
     * @memberof UpdateSettingsFlowWithPasswordMethod
     */
    method: string;
    /**
     * Password is the updated password
     * @type {string}
     * @memberof UpdateSettingsFlowWithPasswordMethod
     */
    password: string;
}

/**
 * Check if a given object implements the UpdateSettingsFlowWithPasswordMethod interface.
 */
export function instanceOfUpdateSettingsFlowWithPasswordMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "method" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UpdateSettingsFlowWithPasswordMethodFromJSON(json: any): UpdateSettingsFlowWithPasswordMethod {
    return UpdateSettingsFlowWithPasswordMethodFromJSONTyped(json, false);
}

export function UpdateSettingsFlowWithPasswordMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSettingsFlowWithPasswordMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'csrf_token': !exists(json, 'csrf_token') ? undefined : json['csrf_token'],
        'method': json['method'],
        'password': json['password'],
    };
}

export function UpdateSettingsFlowWithPasswordMethodToJSON(value?: UpdateSettingsFlowWithPasswordMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'csrf_token': value.csrf_token,
        'method': value.method,
        'password': value.password,
    };
}

