/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The content of the allowed field is mirrored in the HTTP status code.
 * @export
 * @interface CheckPermissionResult
 */
export interface CheckPermissionResult {
    /**
     * whether the relation tuple is allowed
     * @type {boolean}
     * @memberof CheckPermissionResult
     */
    allowed: boolean;
}

/**
 * Check if a given object implements the CheckPermissionResult interface.
 */
export function instanceOfCheckPermissionResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "allowed" in value;

    return isInstance;
}

export function CheckPermissionResultFromJSON(json: any): CheckPermissionResult {
    return CheckPermissionResultFromJSONTyped(json, false);
}

export function CheckPermissionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckPermissionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'allowed': json['allowed'],
    };
}

export function CheckPermissionResultToJSON(value?: CheckPermissionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'allowed': value.allowed,
    };
}

