/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Create Project Request Body
 * @export
 * @interface CreateProjectBody
 */
export interface CreateProjectBody {
    /**
     * The name of the project to be created
     * @type {string}
     * @memberof CreateProjectBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectBody
     */
    workspace_id?: string | null;
}

/**
 * Check if a given object implements the CreateProjectBody interface.
 */
export function instanceOfCreateProjectBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateProjectBodyFromJSON(json: any): CreateProjectBody {
    return CreateProjectBodyFromJSONTyped(json, false);
}

export function CreateProjectBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'workspace_id': !exists(json, 'workspace_id') ? undefined : json['workspace_id'],
    };
}

export function CreateProjectBodyToJSON(value?: CreateProjectBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'workspace_id': value.workspace_id,
    };
}

