/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlowError
 */
export interface FlowError {
    /**
     * CreatedAt is a helper struct field for gobuffalo.pop.
     * @type {Date}
     * @memberof FlowError
     */
    created_at?: Date;
    /**
     * 
     * @type {object}
     * @memberof FlowError
     */
    error?: object;
    /**
     * ID of the error container.
     * @type {string}
     * @memberof FlowError
     */
    id: string;
    /**
     * UpdatedAt is a helper struct field for gobuffalo.pop.
     * @type {Date}
     * @memberof FlowError
     */
    updated_at?: Date;
}

/**
 * Check if a given object implements the FlowError interface.
 */
export function instanceOfFlowError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function FlowErrorFromJSON(json: any): FlowError {
    return FlowErrorFromJSONTyped(json, false);
}

export function FlowErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created_at': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'error': !exists(json, 'error') ? undefined : json['error'],
        'id': json['id'],
        'updated_at': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function FlowErrorToJSON(value?: FlowError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.created_at === undefined ? undefined : (value.created_at.toISOString()),
        'error': value.error,
        'id': value.id,
        'updated_at': value.updated_at === undefined ? undefined : (value.updated_at.toISOString()),
    };
}

