/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
} from './Organization';

/**
 * 
 * @export
 * @interface GetOrganizationResponse
 */
export interface GetOrganizationResponse {
    /**
     * 
     * @type {Organization}
     * @memberof GetOrganizationResponse
     */
    organization: Organization;
}

/**
 * Check if a given object implements the GetOrganizationResponse interface.
 */
export function instanceOfGetOrganizationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "organization" in value;

    return isInstance;
}

export function GetOrganizationResponseFromJSON(json: any): GetOrganizationResponse {
    return GetOrganizationResponseFromJSONTyped(json, false);
}

export function GetOrganizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganizationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organization': OrganizationFromJSON(json['organization']),
    };
}

export function GetOrganizationResponseToJSON(value?: GetOrganizationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organization': OrganizationToJSON(value.organization),
    };
}

