/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Response for a single identity patch
 * @export
 * @interface IdentityPatchResponse
 */
export interface IdentityPatchResponse {
    /**
     * The action for this specific patch
     * create ActionCreate  Create this identity.
     * @type {string}
     * @memberof IdentityPatchResponse
     */
    action?: IdentityPatchResponseActionEnum;
    /**
     * The identity ID payload of this patch
     * @type {string}
     * @memberof IdentityPatchResponse
     */
    identity?: string;
    /**
     * The ID of this patch response, if an ID was specified in the patch.
     * @type {string}
     * @memberof IdentityPatchResponse
     */
    patch_id?: string;
}


/**
 * @export
 */
export const IdentityPatchResponseActionEnum = {
    Create: 'create'
} as const;
export type IdentityPatchResponseActionEnum = typeof IdentityPatchResponseActionEnum[keyof typeof IdentityPatchResponseActionEnum];


/**
 * Check if a given object implements the IdentityPatchResponse interface.
 */
export function instanceOfIdentityPatchResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IdentityPatchResponseFromJSON(json: any): IdentityPatchResponse {
    return IdentityPatchResponseFromJSONTyped(json, false);
}

export function IdentityPatchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityPatchResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'identity': !exists(json, 'identity') ? undefined : json['identity'],
        'patch_id': !exists(json, 'patch_id') ? undefined : json['patch_id'],
    };
}

export function IdentityPatchResponseToJSON(value?: IdentityPatchResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'identity': value.identity,
        'patch_id': value.patch_id,
    };
}

