/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KetoNamespace
 */
export interface KetoNamespace {
    /**
     * 
     * @type {number}
     * @memberof KetoNamespace
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof KetoNamespace
     */
    name?: string;
}

/**
 * Check if a given object implements the KetoNamespace interface.
 */
export function instanceOfKetoNamespace(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KetoNamespaceFromJSON(json: any): KetoNamespace {
    return KetoNamespaceFromJSONTyped(json, false);
}

export function KetoNamespaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): KetoNamespace {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function KetoNamespaceToJSON(value?: KetoNamespace | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

