/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
} from './Organization';

/**
 * B2B SSO Organization List
 * @export
 * @interface ListOrganizationsResponse
 */
export interface ListOrganizationsResponse {
    /**
     * 
     * @type {Array<Organization>}
     * @memberof ListOrganizationsResponse
     */
    organizations: Array<Organization>;
}

/**
 * Check if a given object implements the ListOrganizationsResponse interface.
 */
export function instanceOfListOrganizationsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "organizations" in value;

    return isInstance;
}

export function ListOrganizationsResponseFromJSON(json: any): ListOrganizationsResponse {
    return ListOrganizationsResponseFromJSONTyped(json, false);
}

export function ListOrganizationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganizationsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organizations': ((json['organizations'] as Array<any>).map(OrganizationFromJSON)),
    };
}

export function ListOrganizationsResponseToJSON(value?: ListOrganizationsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organizations': ((value.organizations as Array<any>).map(OrganizationToJSON)),
    };
}

