/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectHost
 */
export interface ProjectHost {
    /**
     * The project's host.
     * @type {string}
     * @memberof ProjectHost
     */
    host: string;
    /**
     * The mapping's ID.
     * @type {string}
     * @memberof ProjectHost
     */
    readonly id: string;
    /**
     * The Revision's Project ID
     * @type {string}
     * @memberof ProjectHost
     */
    project_id: string;
}

/**
 * Check if a given object implements the ProjectHost interface.
 */
export function instanceOfProjectHost(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "host" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "project_id" in value;

    return isInstance;
}

export function ProjectHostFromJSON(json: any): ProjectHost {
    return ProjectHostFromJSONTyped(json, false);
}

export function ProjectHostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectHost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'host': json['host'],
        'id': json['id'],
        'project_id': json['project_id'],
    };
}

export function ProjectHostToJSON(value?: ProjectHost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'host': value.host,
        'project_id': value.project_id,
    };
}

