/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectServiceIdentity
 */
export interface ProjectServiceIdentity {
    /**
     * 
     * @type {object}
     * @memberof ProjectServiceIdentity
     */
    config: object;
}

/**
 * Check if a given object implements the ProjectServiceIdentity interface.
 */
export function instanceOfProjectServiceIdentity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "config" in value;

    return isInstance;
}

export function ProjectServiceIdentityFromJSON(json: any): ProjectServiceIdentity {
    return ProjectServiceIdentityFromJSONTyped(json, false);
}

export function ProjectServiceIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectServiceIdentity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': json['config'],
    };
}

export function ProjectServiceIdentityToJSON(value?: ProjectServiceIdentity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': value.config,
    };
}

