/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Session } from './Session';
import {
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
} from './Session';

/**
 * The Response for Login Flows via API
 * @export
 * @interface SuccessfulNativeLogin
 */
export interface SuccessfulNativeLogin {
    /**
     * 
     * @type {Session}
     * @memberof SuccessfulNativeLogin
     */
    session: Session;
    /**
     * The Session Token
     * 
     * A session token is equivalent to a session cookie, but it can be sent in the HTTP Authorization
     * Header:
     * 
     * Authorization: bearer ${session-token}
     * 
     * The session token is only issued for API flows, not for Browser flows!
     * @type {string}
     * @memberof SuccessfulNativeLogin
     */
    session_token?: string;
}

/**
 * Check if a given object implements the SuccessfulNativeLogin interface.
 */
export function instanceOfSuccessfulNativeLogin(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "session" in value;

    return isInstance;
}

export function SuccessfulNativeLoginFromJSON(json: any): SuccessfulNativeLogin {
    return SuccessfulNativeLoginFromJSONTyped(json, false);
}

export function SuccessfulNativeLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessfulNativeLogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'session': SessionFromJSON(json['session']),
        'session_token': !exists(json, 'session_token') ? undefined : json['session_token'],
    };
}

export function SuccessfulNativeLoginToJSON(value?: SuccessfulNativeLogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'session': SessionToJSON(value.session),
        'session_token': value.session_token,
    };
}

