/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: latest
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GenericUsage } from './GenericUsage';
import {
    GenericUsageFromJSON,
    GenericUsageFromJSONTyped,
    GenericUsageToJSON,
} from './GenericUsage';

/**
 * 
 * @export
 * @interface Usage
 */
export interface Usage {
    /**
     * 
     * @type {GenericUsage}
     * @memberof Usage
     */
    GenericUsage?: GenericUsage;
}

/**
 * Check if a given object implements the Usage interface.
 */
export function instanceOfUsage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsageFromJSON(json: any): Usage {
    return UsageFromJSONTyped(json, false);
}

export function UsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Usage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'GenericUsage': !exists(json, 'GenericUsage') ? undefined : GenericUsageFromJSON(json['GenericUsage']),
    };
}

export function UsageToJSON(value?: Usage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'GenericUsage': GenericUsageToJSON(value.GenericUsage),
    };
}

